[tool.dojo.world]
name = "Underdark"
description = "A generative, on-chain 3D skin-crawler. Something ill under Kurnkornor stirs, down those crumbling old manor stairs. Beware the fading light, and your fraying sanity. Most of all, beware the gibbering of the Slender Duck!"
icon_uri = "https://underdark.vercel.app/images/logo.jpg"
cover_uri = "https://underdark.vercel.app/images/splash.jpg"
website = "https://underdark-splash.vercel.app/"
socials.x = "https://twitter.com/lootunderworld"

[package]
cairo-version = "2.2.0"
name = "underdark"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[dependencies]
# dojo = { git = "https://github.com/dojoengine/dojo.git", rev = "47c0cbcfa4ebd4d4b504ec959fdbcfd3e4271e8a" }
dojo = { git = "https://github.com/dojoengine/dojo.git", tag = "v0.3.1" }


[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
# (the address from Katana log)
account_address = "0x517ececd29116499f4a1b64b094da79ba08dfd54a3edaa316134c41f8160973"
# also from Katana log
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
world_address = "0x6150655e17345af3d45d23f9b1d04a4c5e485dfed5bf55cbd6f53063aaa42a"

